import argparse
import torch


def args_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('--data', type=str, default='fmnist')
    parser.add_argument('--num_agents', type=int, default=10)
    parser.add_argument('--agent_frac', type=float, default=1)
    parser.add_argument('--num_corrupt', type=int, default=0)
    parser.add_argument('--rounds', type=int, default=100)
    parser.add_argument('--aggr', type=str, default='avg')
    parser.add_argument('--local_ep', type=int, default=2)
    parser.add_argument('--corrupt_local_ep', type=int, default=0)
    parser.add_argument('--bs', type=int, default=1024)
    parser.add_argument('--client_lr', type=float, default=0.1)
    parser.add_argument('--client_moment', type=float, default=0.9)
    parser.add_argument('--server_lr', type=float, default=1)
    parser.add_argument('--base_class', type=int, default=5)
    parser.add_argument('--target_class', type=int, default=7)
    parser.add_argument('--poison_frac', type=float, default=0.10)
    parser.add_argument('--pattern_type', type=str, default='plus')
    parser.add_argument('--clean_label', type=int, default=0)
    parser.add_argument('--clean_label_type', type=int, default=0)
    parser.add_argument('--clean_label_auto_pattern', type=int, default=1)
    parser.add_argument('--verify_poisoning', type=int, default=1)
    parser.add_argument('--clean_label_pgd', type=int, default=0)
    parser.add_argument('--pgd_epsilon', type=float, default=16.0/255.0)
    parser.add_argument('--pgd_alpha', type=float, default=2.0/255.0)
    parser.add_argument('--pgd_steps', type=int, default=5)
    parser.add_argument('--malicious_boost', type=float, default=1.0)
    parser.add_argument('--robustLR_threshold', type=int, default=0)
    parser.add_argument('--clip', type=float, default=0)
    parser.add_argument('--noise', type=float, default=0)
    parser.add_argument('--top_frac', type=int, default=100)
    parser.add_argument('--snap', type=int, default=1)
    parser.add_argument('--device', default=torch.device('cuda:0' if torch.cuda.is_available() else 'cpu'))
    parser.add_argument('--num_workers', type=int, default=0)

    parser.add_argument('--cuckoo', type=int, default=0)
    parser.add_argument('--cuckoo_variant', type=str, default='v1_biology_nest')
    parser.add_argument('--cuckoo_diag_every', type=int, default=10)
    parser.add_argument('--cuckoo_v1_lambda', type=float, default=1.20)
    parser.add_argument('--cuckoo_v1_incubation_lambda', type=float, default=0.0)
    parser.add_argument('--cuckoo_v1_hatch_round', type=int, default=8)
    parser.add_argument('--cuckoo_v1_warmup_rounds', type=int, default=20)
    parser.add_argument('--cuckoo_v1_schedule', type=str, default='cosine')
    parser.add_argument('--cuckoo_v1_top_frac', type=float, default=0.22)
    parser.add_argument('--cuckoo_v1_egg_budget_mult', type=float, default=0.85)
    parser.add_argument('--cuckoo_v1_norm_cap', type=float, default=1.40)
    parser.add_argument('--cuckoo_v1_min_cosine', type=float, default=0.15)
    parser.add_argument('--cuckoo_v1_sign_align', type=int, default=1)
    parser.add_argument('--cuckoo_v1_sign_relax', type=float, default=0.05)
    parser.add_argument('--cuckoo_v1_memory', type=int, default=1)
    parser.add_argument('--cuckoo_v1_memory_decay', type=float, default=0.85)
    parser.add_argument('--cuckoo_v1_memory_carry', type=float, default=0.20)
    parser.add_argument('--cuckoo_v1_host_ema', type=float, default=0.0)
    parser.add_argument('--cuckoo_v1_host_mag_bonus', type=float, default=0.20)
    parser.add_argument('--cuckoo_v1_sign_bonus', type=float, default=0.40)
    parser.add_argument('--cuckoo_v1_classifier_boost', type=float, default=1.5)
    parser.add_argument('--cuckoo_v1_target_row_boost', type=float, default=3.0)
    parser.add_argument('--cuckoo_v1_base_row_boost', type=float, default=1.8)
    parser.add_argument('--cuckoo_v1_bias_boost', type=float, default=1.25)
    parser.add_argument('--cuckoo_v1_include_bias', type=int, default=1)
    parser.add_argument('--cuckoo_v1_row_focus', type=str, default='target_base')
    parser.add_argument('--cuckoo_v1_center_egg', type=int, default=1)
    parser.add_argument('--cuckoo_v1_preserve_blend', type=float, default=0.03)
    return parser.parse_args()
